language: generic 
sudo: required 
services:
  - docker

before_install:
  - docker build -t alessandromacri/docker-simple-react-fe  -f Dockerfile.dev .

script:
  - docker run -e CI=true alessandromacri/docker-simple-react-fe npm test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-simple-react-fe"
  env: "Dockersimplereactfe-env"
  bucket_name: "elasticbeanstalk-us-east-2-887002784570"
  bucket_path: "docker-simple-react-fe"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY